CREATE TABLE LANDING_CRAMERQA.CDC_GG_TIPDOC (
  COD_TIPDOC CHAR(2) NOT NULL,
  DES_TIPDOC CHAR(30) NOT NULL,
  IND_ESTADO CHAR(1) NOT NULL,
  COD_USUARI CHAR(10) NOT NULL,
  FEC_AUDITA DATE NOT NULL,
  IND_DOCTO CHAR(1),
  DES_ARCHIVO CHAR(15),
  DES_ARCCAB CHAR(15),
  DES_ARCDET CHAR(15),
  op CHAR(1),
  ts_ms TIMESTAMPTZ,
  uuid_nifi VARCHAR(36) NOT NULL,
  kafka_offset BIGINT,
  tipo VARCHAR(6),
  procesado BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (COD_TIPDOC,uuid_nifi,tipo)
);

CREATE TABLE LANDING_CRAMERQA.CGG_TIPDOC (
  COD_TIPDOC CHAR(2) NOT NULL,
  DES_TIPDOC CHAR(30) NOT NULL,
  IND_ESTADO CHAR(1) NOT NULL,
  COD_USUARI CHAR(10) NOT NULL,
  FEC_AUDITA DATE NOT NULL,
  IND_DOCTO CHAR(1),
  DES_ARCHIVO CHAR(15),
  DES_ARCCAB CHAR(15),
  DES_ARCDET CHAR(15),
  op CHAR(1),
  ts_ms TIMESTAMPTZ,
  uuid_nifi VARCHAR(36) NOT NULL,
  kafka_offset BIGINT,
  tipo VARCHAR(6),
  PRIMARY KEY (COD_TIPDOC,uuid_nifi,tipo)
);