CREATE TABLE api_freshdesk_sistemas.conversations(
  id BIGINT,
  body TEXT,
  body_text TEXT,
  structured_body TEXT,
  incoming BOOLEAN,
  private BOOLEAN,
  user_id BIGINT,
  support_email TEXT,
  source INT,
  category INT,
  to_emails TEXT,
  from_email TEXT,
  cc_emails TEXT,
  bcc_emails TEXT,
  email_failure_count INT,
  outgoing_failures INT,
  thread_id BIGINT,
  thread_message_id BIGINT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  last_edited_at TEXT,
  last_edited_user_id BIGINT,
  attachments TEXT,
  automation_id BIGINT,
  automation_type_id BIGINT,
  auto_response BOOLEAN,
  ticket_id BIGINT,
  threading_type TEXT,
  delivery_details JSONB,
  source_additional_info TEXT,
  timestamp_nifi TIMESTAMPTZ,
  PRIMARY KEY (id)
  );