CREATE TABLE IF NOT EXISTS api_freshdesk_regulaciones.tickets (
  id BIGINT,
  fwd_emails TEXT,
  reply_cc_emails TEXT,
  ticket_cc_emails TEXT,
  ticket_bcc_emails TEXT,
  fr_escalated BOOLEAN,
  spam BOOLEAN,
  email_config_id BIGINT,
  group_id BIGINT,
  priority INT,
  requester_id BIGINT,
  responder_id BIGINT,
  source INT,
  company_id BIGINT,
  status INT,
  subject VARCHAR(255),
  association_type VARCHAR(50),
  support_email TEXT,
  to_emails TEXT,
  product_id BIGINT,
  type VARCHAR(50),
  due_by TIMESTAMP,
  fr_due_by TIMESTAMP,
  is_escalated BOOLEAN,
  custom_fields JSONB,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  associated_tickets_count INT,
  tags TEXT,
  description TEXT,
  description_text TEXT,
  deleted BOOLEAN,
  requester JSONB,
  stats JSONB,
  structured_description TEXT,
  nr_due_by INT,
  nr_escalated BOOLEAN,
  timestamp_nifi TIMESTAMPTZ,
  PRIMARY KEY (id)
);

https://cramerit.freshdesk.com/api/v2/tickets?include=description,stats,requester&per_page=100&order_type=asc&page=114&updated_since=2020-01-01T00:00:00Z