services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - GITEA__server__DOMAIN=${GITEA_DOMAIN}
      - GITEA__server__ROOT_URL=${GITEA_ROOT_URL}
      - GITEA__server__SSH_DOMAIN=${GITEA_SSH_DOMAIN}
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - ./gitea:/data
    networks:
      - gitea_net

networks:
  gitea_net:
    driver: bridge
    name: gitea_net
