create or replace pipe LANDING.CRAMERQA.PIPE_CDC_GG_TIPDOC auto_ingest=false as COPY INTO LANDING.CRAMERQA.CDC_GG_TIPDOC
FROM @LANDING.CRAMERQA.%CDC_GG_TIPDOC
FILE_FORMAT = (
    TYPE = 'CSV',
    FIELD_DELIMITER = ',',
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ESCAPE = '\\',
    MULTI_LINE = TRUE,
    PARSE_HEADER = TRUE,  
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

create or replace pipe LANDING.CRAMERQA.PIPE_CDC_GG_TPAIS auto_ingest=false as COPY INTO LANDING.CRAMERQA.CDC_GG_TPAIS
FROM @LANDING.CRAMERQA.%CDC_GG_TPAIS
FILE_FORMAT = (
    TYPE = 'CSV',
    FIELD_DELIMITER = ',',
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ESCAPE = '\\',
    MULTI_LINE = TRUE,
    PARSE_HEADER = TRUE,  
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

create or replace pipe LANDING.CRAMERQA.PIPE_CDC_VT_DETFAC auto_ingest=false as COPY INTO LANDING.CRAMERQA.CDC_VT_DETFAC
FROM @LANDING.CRAMERQA.%CDC_VT_DETFAC
FILE_FORMAT = (
    TYPE = 'CSV',
    FIELD_DELIMITER = ',',
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ESCAPE = '\\',
    MULTI_LINE = TRUE,
    PARSE_HEADER = TRUE,  
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;