services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver_test
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    environment:
      CB_SERVER_NAME: CloudBeaver
      CB_ADMIN_NAME: ${CB_ADMIN_NAME}
      CB_ADMIN_PASSWORD: ${CB_ADMIN_PASSWORD}
    networks:
      - airflow_net
      - debezium_net
      - debezium_net_v2
      - gitea_net
      - bi_postgres_net

volumes:
  cloudbeaver_data:
    driver: local

networks:
  airflow_net:
    external: true
    name: cloudbeaver_airflow_net
  debezium_net:
    external: true
    name: kafkaydebezium_debezium_net
  debezium_net_v2:
    external: true
    name: debezium_net_v2_latest
  gitea_net:
    external: true
    name: gitea_net
  bi_postgres_net:
    external: true
    name: bi_postgres_net