services:
  nifi:
    image: apache/nifi:2.5.0
    container_name: nifi
    restart: on-failure
    ports:
      - "8443:8443"  # Puerto HTTPS para la interfaz web
    environment:
      # Configuración para permitir acceso por IP
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_PROXY_HOST=${SERVER_IP}:8443
      # Configuración de seguridad (desarrollo)
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME:-nifi}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD:-ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB}
      - NIFI_SECURITY_ALLOW_ANONYMOUS_AUTHENTICATION=false
      # Configuración de timezone
      - TZ=America/Santiago
      
    volumes:
      # Drivers JDBC personalizados (RUTA CORREGIDA)
      - ./nifi/jdbc:/opt/nifi/nifi/jdbc
      # Ruta para guardar procesadores personalizados (NARs)
      - ./nifi/nars:/opt/nifi/nifi-current/nar_extensions
      
      # Carpeta para archivos de entrada
      - ./nifi/input:/opt/nifi/input
      # Carpeta para ejecutables
      - ./nifi/ejecutables:/opt/nifi/ejecutables
      
      # Carpeta para archivos de salida (NUEVA - para PutFile)
      - ./nifi/output:/opt/nifi/output
      
      # Datos persistentes
      - nifi-logs:/opt/nifi/nifi-current/logs
      - nifi-conf:/opt/nifi/nifi-current/conf
      - nifi-content_repository:/opt/nifi/nifi-current/content_repository
      - nifi-database_repository:/opt/nifi/nifi-current/database_repository
      - nifi-flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi-provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi-state:/opt/nifi/nifi-current/state
      
    networks:
      - nifi_net
      - bi_postgres_net

volumes:
  # Volúmenes para NiFi (sin driver: local redundante)
  nifi-logs:
  nifi-conf:
  nifi-content_repository:
  nifi-database_repository:
  nifi-flowfile_repository:
  nifi-provenance_repository:
  nifi-state:

networks:
  nifi_net:
    driver: bridge
    name: nifi_net
  bi_postgres_net:
    external: true
    name: bi_postgres_net